Added *.provenance.update_date, bundle_uuid, and bundle_version columns
HumanCellAtlas/hca_bundles_to_csv pull request #10
Opened 2019-05-07 20:32 UTC by GPelayo

2019-05-08 03:11 UTC, hannes-ucsc approved these changes

2019-05-10 08:37 UTC, simonjupp commented
I would put provenance information and uuid towards the end of the column. These are ugly values and the TSV is about presenting the metadata in a more human friendly form. Can you switch the default order to put the provenance columns towards the last rows?

2019-05-10 08:37 UTC, simonjupp requested changes
I would put provenance information and uuid towards the end of the column. These are ugly values and the TSV is about presenting the metadata in a more human friendly form. Can you switch the default order to put the provenance columns towards the last columns?

2019-05-10 21:07 UTC, GPelayo commented on hca_bundle_tools/file_metadata_to_csv.py
> -            obj["*.provenance.document_id"] = self._deep_get(content, ["provenance", "document_id"])
Not needed. There are already columns with the file's document id.

2019-05-13 12:53 UTC, simonjupp approved these changes

2019-05-14 17:57 UTC, merged